apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-embedding-to-qdrant
  namespace: quarkrag
spec:
  podSelector:
    matchLabels:
      app: qdrant
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: embedding-service
      ports:
        - protocol: TCP
          port: 6333
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-embedding-to-qdrant
  namespace: quarkrag
spec:
  podSelector:
    matchLabels:
      app: embedding-service
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: qdrant
      ports:
        - protocol: TCP
          port: 6333
