apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-query-to-redis
  namespace: quarkrag
spec:
  podSelector:
    matchLabels:
      app: redis
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: query-service
      ports:
        - protocol: TCP
          port: 6379
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-query-to-redis
  namespace: quarkrag
spec:
  podSelector:
    matchLabels:
      app: query-service
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: redis
      ports:
        - protocol: TCP
          port: 6379
