apiVersion: v1
kind: ConfigMap
metadata:
  name: quarkrag-config
  namespace: quarkrag
data:
  # Database Configurations
  QDRANT_HOST: "$QDRANT_HOST"
  QDRANT_PORT: "$QDRANT_PORT"
  REDIS_URL: "$REDIS_URL"
  KAFKA_BROKER_URL: "$KAFKA_BROKER_URL"
  
  # Service URLs
  LLM_PROVIDER_SERVICE_URL: "$LLM_PROVIDER_SERVICE_URL"
  
  # Observability
  OTEL_EXPORTER_OTLP_ENDPOINT: "$OTEL_EXPORTER_OTLP_ENDPOINT"
  
  # Application Config
  EMBEDDING_PROVIDER: "$EMBEDDING_PROVIDER"
  OLLAMA_URL: "$OLLAMA_URL"
  OLLAMA_MODEL_NAME: "$OLLAMA_MODEL_NAME"
